export const store = [
    {id: 1, name: "Attack on Titan", altname: "Shingeki no Kyojin", description: "Driven into perspective, it reaches the last days under the yoke of the titans - mysterious creatures that terrorize the human race. The survivors huddle behind the walls of a large settlement with features that represent the last stronghold of central authority in the world. A young man named Eren also lives there, spending his childhood in relative safety, until an out of the ordinary event occurs: the titans break into the city, destroying everything in their path. After the second defeat of the giants, Eren becomes an orphan and vows to destroy every single titan. On the way to his goal, he and his friends are part of a reconnaissance squad engaged in sorties over the wall. The hero does not yet know how many mysteries the outside world is fraught with.\nA snapshot of the manga about the adventures of Eren and his comrades Shingeki no Kyojin \"blew up\" the global anime community in 2013 and attracted many fans of Japanese animation.", yearOfCreation: "2013", genres: ["Shounen", "Adventure", "Action", "Drama", "Fantasy", "Thriller"], img: "https://static.wikia.nocookie.net/shingekinokyojin/images/1/12/Season_1_key_visual_%28clean_version%29.jpeg"},
    {id: 2, name: "Demon Slayer", altname: "Kimetsu no Yaiba", description: "", yearOfCreation: "", genres: ["Shounen", "Mystery", "Action"], img: "https://i.pinimg.com/1200x/ee/e7/4d/eee74d7eaa1cb288c295fe79fda2a4db.jpg"},
    {id: 3, name: "Jobless Reincarnation", altname: "Mushoku Tensei", description: "", yearOfCreation: "", genres: ["Isekai", "Drama", "Fantasy", "Adventure"], img: "https://m.media-amazon.com/images/I/715-vl+FkNL._AC_UF894,1000_QL80_.jpg"},
    {id: 4, name: "My Hero Academia", altname: "Boku no Hero", description: "", yearOfCreation: "", genres: ["Shounen", "Fantasy", "Adventure", "Action"], img: "https://m.media-amazon.com/images/I/7103o243KEL.jpg"},
    {id: 5, name: "Jujutsu Kaisen", altname: "呪術廻戦", description: "", yearOfCreation: "", genres: ["Shounen, Fantasy, Action"], img: "https://m.media-amazon.com/images/I/71bo0vTsYVL.jpg"},
    {id: 6, name: "Mob Psycho 100", altname: "モブサイコ100", description: "", yearOfCreation: "", genres: [], img: "https://m.media-amazon.com/images/I/71cFCD5GmyL.jpg"},
    {id: 7, name: "One Punch Man", altname: "ワンパンマン", description: "", yearOfCreation: "", genres: [], img: "https://m.media-amazon.com/images/I/71wrGSJlofL._AC_UF894,1000_QL80_.jpg"},
    {id: 8, name: "One Piece", altname: "ワンピース", description: "", yearOfCreation: "", genres: [], img: "https://cdn.europosters.eu/image/1300/posters/one-piece-big-mom-saga-i94377.jpg"},
    {id: 9, name: "Seven Deadly Sins", altname: "Nanatsu no Taizai", description: "", yearOfCreation: "", genres: [], img: "https://m.media-amazon.com/images/I/81Uu-Z2zYhL.jpg"},
    {id: 10, name: "Dororo", altname: "どろろ", description: "", yearOfCreation: "", genres: [], img: "https://www.arthipo.com/image/cache/catalog/poster/anime/1-699/anime244-dororo-manga-poster-print-sales-high-resolution-image-download-1000x1000.webp"},
    {id: 11, name: "Tokyo Revengers", altname: "東京卍リベンジャーズ", description: "", yearOfCreation: "", genres: [], img: "https://www.arthipo.com/image/cache/catalog/poster/anime/1342-1897/anime1838-tokyo-revengers-6-manga-poster-print-sales-high-resolution-image-download-778x1100.webp"},
    {id: 12, name: "Tokyo Ghoul", altname: "東京喰種", description: "", yearOfCreation: "", genres: [], img: "https://m.media-amazon.com/images/I/615UoMEsDEL.jpg"}
  ];